qmk/qmk_cli

qmk_cli/script_qmk.py
When running the global cli within qmk/qmk_base_container#5, it produces the following output:
```console
Traceback (most recent call last):
File "/usr/local/bin/qmk", line 11, in <module>
sys.exit(main())
File "/usr/local/lib/python3.5/dist-packages/qmk_cli/script_qmk.py", line 67, in main
qmk_firmware = find_qmk_firmware()
File "/usr/local/lib/python3.5/dist-packages/qmk_cli/script_qmk.py", line 54, in find_qmk_firmware
if in_qmk_firmware():
File "/usr/local/lib/python3.5/dist-packages/qmk_cli/script_qmk.py", line 37, in in_qmk_firmware
result = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
File "/usr/lib/python3.5/subprocess.py", line 383, in run
with Popen(*popenargs, **kwargs) as process:
File "/usr/lib/python3.5/subprocess.py", line 676, in __init__ …
```
=> Fix in_qmk_firmware for Python 3.5

milc.py
When rigging up some initial CI process, It was noticed that on Windows it would error out.
```console
Traceback (most recent call last):
File "./qmk", line 4, in <module>
import qmk_cli.script_qmk
File "C:\Users\travis\build\zvecr\qmk_cli\qmk_cli\script_qmk.py", line 16, in <module>
import milc
File "C:\Users\travis\build\zvecr\qmk_cli\milc.py", line 42, in <module>
logging.basicConfig(filename='/dev/null')
File "C:\Python\lib\logging\__init__.py", line 1973, in basicConfig
h = FileHandler(filename, mode)
File "C:\Python\lib\logging\__init__.py", line 1143, in __init__
StreamHandler.__init__(self, self._open())
File "C:\Python\lib\logging\__init__.py", line 1172, in _open
return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or …
```
=> Fix No such file or directory: 'C:\\dev\\null'

qmk_cli/subcommands/setup.py
Setup raised a `TypeError`, because of the wrong variable name. Now it can clone the git repo.
=> Fix command line variable access for baseurl and branch

milc.py
This is the same change as in: https://github.com/qmk/qmk_firmware/pull/8148
Replace `os.rename` with `os.replace` for cross platform overwrite support
=> Replace rename with replace

qmk_cli/script_qmk.py
Windows fails with a mysterious error message under mysterious circumstances if we don't provide the interpreter for shells.
=> Fix WinError 193 on MSYS2

qmk_cli/subcommands/setup.py
When 'qmk setup' is started with the '-y' argument, this argument should be specified for 'qmk doctor' as well.
=> Fix argument passing to doctor subcommand

qmk_cli/script_qmk.py, qmk_cli/subcommands/setup.py
Attempting `qmk setup` to a non standard location, it was spitting out the following error:
```console
Traceback (most recent call last):
File "/home/zvecr/.local/bin/qmk", line 10, in <module>
sys.exit(main())
File "/home/zvecr/.local/lib/python3.7/site-packages/qmk_cli/script_qmk.py", line 85, in main
import qmk.cli
ModuleNotFoundError: No module named 'qmk'
```
Took a while to realise it was due to the target folder existing, but empty. Removing the empty folder worked, but working round that is potentially a little friendlier to end users.
This also fixes `qmk setup zvecr/qmk_firmware .` to install directly to the current directory.
=> Protect against empty QMK_HOME folder

qmk_cli/script_qmk.py
Warn MSYS2 users that the are not in the MINGW64 shell.
This does not affect WSL or other platforms.
This is just a warning, so already set up environments can be used.
=> Add warning message for MSYS users

milc.py, qmk_cli/git.py, qmk_cli/helpers.py, qmk_cli/subcommands/clone.py, qmk_cli/subcommands/setup.py
Improve how `qmk setup` works by allowing people to specify a destination without specifying a fork. It also offers to set the location for `qmk_firmware` in `user.qmk_home`.
This should make it easier for people who want to put `qmk_firmware` somewhere other than their home directory.
=> improve the qmk setup flow

qmk_cli/script_qmk.py
The return code provided by `milc.cli()` is discarded. This adds the same logic as in https://github.com/qmk/qmk_firmware/blob/6499eb6a3c512ded96443649d66274ce1064df0f/bin/qmk#L81-L93 to exit the CLI with the proper return code.
=> Fix CLI not producing any return codes

qmk_cli/script_qmk.py
This should really be an error, as setting up QMK in the MSYS or MinGW32 terminals just won't work - the mingw64 versions of packages are installed, as well as Python itself, so `qmk setup` will give `command not found` anyway.
=> Change MSYS2 terminal warning to an error

qmk_cli/helpers.py, qmk_cli/script_qmk.py
This brings in the logic from `bin/qmk` that checks for requirements. If the check fails we don't pull in local subcommands (but still allow global subcommands to work.)
As a bonus this imports milc's config subcommand, allowing users to still change their qmk configuration even when there's a problem with qmk_firmware (EG, `user.developer=None`.)
=> Check if requirements are installed before importing qmk_firmware

qmk_cli/subcommands/setup.py
Prevents `qmk setup` asking if you want to set `QMK_HOME` even if it is already set.
=> Path-ify QMK_HOME

.github/workflows/cli_setup.yml
`mingw-w64-x86_64-python-pip` depends on `mingw-w64-x86_64-python-setuptools` so there is no real need to install them through pip.
=> [MSYS2] Remove explicit setuptools upgrade from build action

qmk_cli/subcommands/__init__.py, qmk_cli/subcommands/env.py
Needed a way to query the location of `qmk_firmware` for backup purposes. This way potentially allows the folder to be a bit more dynamic than assuming its in home, or sniffing the conf file which downstream processes do not own.
The basic logic to be implemented is `if backup_enabled and qmk_firmware.exists()`, to which might execute before `qmk_setup` has run or without the config file being written.
Right now it just spits out `QMK_HOME` value and the general section of `cli.config`, in a way that partially mimics `go env`. This could be extended to output stuff like the entire contents of `qmk config` or other runtime stuff like the `broken_module_imports` status.
=> Add env subcommand

qmk_cli/script_qmk.py, qmk_cli/subcommands/setup.py, setup.py
Set the CLI version using the new `set_metadata()` function in MILC 1.4.0. `qmk --version` finally returns some useful information!
Also fixed an apparent bug with ZSH on MSYS2; it does not seem to like backslashes (anymore?). Massaging it with Pathlib appears to make it work again.
=> Updates for milc 1.4.0

setup.py
The dotty-dict package has UTF-8 characters in the metadata, which certain non-UTF8 locales error out on. This switches to a qmk provided package that does not have that problem.
=> Switch to the qmk-dotty-dict package

qmk_cli/subcommands/console.py
Add support for QMK HID Bootloader detection. 
Mirrors changes from https://github.com/qmk/qmk_firmware/pull/14038
=> Add LUFA/QMK HID Bootloader support

qmk_cli/subcommands/console.py
- Change `USBasp` and `bootloadHID` to `usbasploader` and `bootloadhid`, per https://github.com/qmk/qmk_firmware/pull/14354
- Fix typo "Polou" -> "Pololu"
- Reordered `lufa-ms` and `qmk-hid`
=> Update bootloader list

.github/workflows/docker-republish.yml
Right now, the only way to pick up latest base_container changes be to bump patch which seems unnecessary.
This will then address a few things:
* `qmk_firmware` CI not using the latest dependencies
* bleh workarounds <https://github.com/qmk/qmk_distro_wsl/pull/34> in dependent projects
=> Add workflow to rebuild docker image

setup.cfg
Bump the installed version of jsonschema to >=4 so we have access to the
validator of the latest meta-schema.
As we already request >=3, installations after 2021-11-30 should satisfy
the new requirements.
=> Bump the 'jsonschema' version

qmk_cli/subcommands/clone.py, qmk_cli/subcommands/env.py, qmk_cli/subcommands/setup.py
User on discord was confused over why setting `setup.fork` did not work (code would have to be updated to use the alternative location `cli.config.setup.fork`). The assumption begins with items in `qmk config -a` being valid config options.
Doesnt seem to make much sense having config options for setup and clone? The current mixture of args and config just seems to be more complicated than it needs to be because of it.
=> Disable use of config for setup|clone

setup.cfg
https://github.com/msys2/MINGW-packages/pull/11635 (seems to be the recommended method of installing Python packages in MSYS2)
https://github.com/pawelzny/dotty_dict/pull/87 (needs merge + release)
qmk_firmware MSYS2 install script will also need to be updated to install the MSYS2 Python packages.
=> Revert dependency on qmk-dotty-dict

qmk_cli/subcommands/setup.py
If a user...
1. Already has a valid home setup
2. Chooses to run `qmk setup` with a "new" home
3. Does not set home when prompted
`qmk doctor` is incorrectly run in the original home, rather than the new.
=> Run `qmk doctor` in the correct directory

qmk_cli/subcommands/console.py
Seems including a `%` in the console output throws errors.
See https://github.com/qmk/qmk_firmware/pull/20238
Seems like a potential bug in `milc` but we don't have access to that.
Tested using:
```sh
python3 -m pip uninstall -y qmk
python3 -m pip install git+https://github.com/qmk/qmk_cli.git@attempted-formatting-fix
```
=> Formatting fix.

qmk_cli/subcommands/console.py
Add WB32 bootloader to `qmk_console`.
=> feat: wb32 bootloader

.github/workflows/cli_setup.yml, ci_tests, setup.cfg
=> milc bump to 1.6.8, add python 3.10-3.12.

.github/workflows/cli_setup.yml, .github/workflows/docker-republish.yml, .github/workflows/python-publish.yml, qmk_cli/script_qmk.py, setup.cfg
From https://github.com/qmk/qmk_firmware/pull/23989
```py
#
```
Notes:
* macos runners are unable to install the older versions of python
* Single x64 macos job has been added now `macos-latest` points to Arm64
* Fixed windows execution
* pypa/build#736 now attempts to use system `pip`
* msys2 packaging strips out some of the required dependencies <https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-python-pip/PKGBUILD#L38>
* Bodge reinstall of pip via pypi with the required files
=> Bump minimum python version to 3.9

qmk_cli/subcommands/console.py
I've noticed a slight inconsistency in the messages output by `qmk console`.
Adjust the format string for the error message printed when `qmk console` cannot connect to the device.
Before:
After:
(notice the changes around the device ID and detailed error message at the end)
=> Adjust format string for could-not-connect message in console

qmk_cli/helpers.py, qmk_cli/script_qmk.py, qmk_cli/subcommands/env.py
* Removes the requirement on running `qmk config user.overlay_dir="$(realpath qmk_userspace)"` 
* Allows multiple userspace instances by inferring from the current directory
* Adds `qmk env QMK_USERSPACE` for scripting purposes
=> Automatically configure userspace at runtime

qmk_cli/script_qmk.py
As per the title. Bootstrap script prereq.
=> Windows `uv` compat.

setup.cfg
This fixes the following bug in Debian:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1083736
The setuptools dependency is not needed in this file because setuptools will be installed from the pyproject.toml file. Since the project does not use anything from the setuptools package, remove it as a dependency.
=> setup.cfg: drop setuptools dependency
